# CONTAINER MICRO-FE CONFIG FILE
name: deploy-marketing
on:
  push:
    branches: [ develop ]
    workflow_dispatch:
jobs:
  build:
    # VM to use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node_modules
        run: npm install

      - name: Build WebApp
        run: npm run-script build

      # --- AWS S3 DEPLOYMENT ---

      # DEV Credentials config
      - name: Configure AWS credentials from DEV Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # DEV WebSite Deployment
      - name: Copy files to the DEV website with the AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/marketing/latest

      - name: AWS CloudFront Cache Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"
